name: Complete Workflow Syntax Example

# Comprehensive example showing various workflow features
on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  # Global environment variables
  NODE_VERSION: '18'
  GREETING: 'Hello from GitHub Actions!'

jobs:
  # Job 1: Basic setup and information
  setup:
    runs-on: ubuntu-latest
    
    # Job-level environment variables
    env:
      JOB_NAME: 'setup-job'
    
    # Job outputs (can be used by other jobs)
    outputs:
      timestamp: ${{ steps.timestamp.outputs.time }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set timestamp
        id: timestamp
        run: echo "time=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      
      - name: Display environment
        run: |
          echo "🌍 Global env - NODE_VERSION: $NODE_VERSION"
          echo "🌍 Global env - GREETING: $GREETING"
          echo "🏷️  Job env - JOB_NAME: $JOB_NAME"
          echo "⏰ Timestamp: ${{ steps.timestamp.outputs.time }}"
  
  # Job 2: Conditional job that depends on setup
  conditional-job:
    runs-on: ubuntu-latest
    needs: setup
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Run only on main branch
        run: |
          echo "🎯 This job only runs on main branch"
          echo "⏰ Setup completed at: ${{ needs.setup.outputs.timestamp }}"
  
  # Job 3: Matrix strategy example
  matrix-demo:
    runs-on: ${{ matrix.os }}
    needs: setup
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [16, 18, 20]
      fail-fast: false
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      
      - name: Display matrix info
        run: |
          echo "🖥️  OS: ${{ matrix.os }}"
          echo "📦 Node version: ${{ matrix.version }}"
          node --version