name: Daily Cron Job Demo

on:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes

jobs:
  run-daily-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run daily script
        run: echo "Hello! This script runs every day at midnight."
