name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy-to-s3:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: List files before sync
        run: ls -la section-6-aws-deploy/deploy-static-s3/dist/
          

      - name: Sync dist/ to S3
        run: |
          aws s3 sync section-6-aws-deploy/deploy-static-s3/dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ \
            --delete

      - name: Invalidate CloudFront (optional)
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        if: env.DIST_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/*"
